### ISSUE TITLE
Logo Proposal for Quiz Mulado

### ISSUE THREAD

**Issue by mendezand** [DoisLucas/QuizMulado-Unity-CSharp#1]
Oi, como vai? Eu criei um logo plano para o Quiz Mulado. Quaisquer modificações não hesite em perguntar. Eu te envio uma prévia.

![captura](https://user-images.githubusercontent.com/38763253/39681780-318222d8-517a-11e8-8bb8-6e0d08575aa3.PNG)

PD: Estou usando um tradutor para se comunicar com você, desculpe se há um erro na escrita.

**Comment by DoisLucas** [comment]
Muito obrigado por contribuir com o projeto, sua logo ficou ótima, porém já possuo toda identidade visual da aplicação, caso não tivesse, aceitaria com certeza sua proposta. Mais uma vez obrigado!
